マイルストーン編集用のfetchロジックを作る
openhacku-team-a/a-project-frontend pull request #39
Opened 2024-03-14 13:01 UTC by hirokiwa

## PRで実装される機能

* マイルストーンの編集のためのfetchを行うカスタムフックを作成する

## PRで修正される機能

## レビューをお願いしたいポイント

2024-03-14 13:02 UTC, hirokiwa commented on src/hooks/useFetchMilestone.ts
> +  }
マイルストーンを取得する関数

2024-03-14 13:03 UTC, hirokiwa commented on src/hooks/useFetchMilestone.ts
> +  }
マイルストーンを新規作成する関数

2024-03-14 13:03 UTC, hirokiwa commented on src/hooks/useFetchMilestone.ts
> +  }
マイルストーンを更新する関数

2024-03-14 13:03 UTC, hirokiwa commented on src/hooks/useFetchMilestone.ts
> +}
マイルストーンを削除する関数

2024-03-15 21:37 UTC, daiki0381 approved these changes
LGTM

2024-03-15 21:47 UTC, shion1305 requested changes

2024-03-15 21:47 UTC, shion1305 commented on src/hooks/useFetchUser.ts
> +const protobuf = require("protobufjs");
```suggestion
```

2024-03-15 21:47 UTC, shion1305 commented on src/hooks/useFetchMilestone.ts
> +const protobuf = require("protobufjs");
```suggestion
```

2024-03-15 21:47 UTC, shion1305 commented on src/hooks/useImageUploder.ts
> +};
```suggestion
const useImageUploder = () => {
  const upload = async (image: File): Promise<string | void> => {
    const token = localStorage.getItem("token");
  };
  return { upload };
};
```

2024-03-15 21:47 UTC, shion1305 commented on src/hooks/useFetchMilestone.ts
> +      .put(`/milestone/${newMilestoen.milestone?.milestoneId}`, newMilestoen)
clientなんですが 現状 `/api/v1/` つけないといけない仕様になっています..

2024-03-15 22:29 UTC, shion1305 approved these changes

2024-03-15 22:29 UTC, merged